# This is a basic workflow that is manually triggered

name: Announcement

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      postTitle:
        description: 'Title of the Post'
        default: 'Fancy title'
        required: true
      postLink:
        description: 'Link to the Post'
        default: 'Insert link here'
        required: true
        
  
env:
  WEBHOOK: "${{secrets.DISCORD_ANNOUNCEMENT_WEBHOOK}}"
  LINK: "${{github.events.input.postLink}}"
  TITLE: "${{github.events.input.postTitle}}"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  shout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: sh ./announcement.sh
        
