# This is a basic workflow that is manually triggered

name: Announcement

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      postTitle:
        description: 'Title of the Post'
        default: 'Fancy title'
        required: true
      postLink:
        description: 'Link to the Post'
        default: 'Insert link here'
        required: true
        
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  shout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run:  curl -X POST "${{DISCORD_ANNOUNCEMENT_WEBHOOK}}" -d "content=:pepefrog: @everyone :pepefrog:\nNew post! Check it out here: [${{github.events.input.postLink}}](${{postTitle}})"
